"""Train the DenseNet121 pneumonia classifier (two-phase transfer learning).

Phase 1  – freeze the DenseNet backbone, train only the new head.
Phase 2  – unfreeze the top of the backbone and fine-tune with a low LR.

After training, the model is saved to ``models/`` and evaluation figures +
metrics are generated by ``src.evaluate``.

Run::

    python -m src.train
"""
from __future__ import annotations

import json

import matplotlib

matplotlib.use("Agg")  # headless backend for saving figures
import matplotlib.pyplot as plt
import tensorflow as tf

from . import config, data_loader, evaluate, model as model_lib


def _plot_history(histories: list, path) -> None:
    """Plot accuracy & loss curves across both training phases."""
    acc, val_acc, loss, val_loss = [], [], [], []
    for h in histories:
        acc += h.history.get("accuracy", [])
        val_acc += h.history.get("val_accuracy", [])
        loss += h.history.get("loss", [])
        val_loss += h.history.get("val_loss", [])

    epochs = range(1, len(acc) + 1)
    fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(12, 4.5))

    ax1.plot(epochs, acc, "o-", label="Train")
    ax1.plot(epochs, val_acc, "s-", label="Validation")
    ax1.axvline(config.HEAD_EPOCHS + 0.5, ls="--", c="grey", alpha=0.7)
    ax1.set_title("Accuracy"); ax1.set_xlabel("Epoch"); ax1.set_ylabel("Accuracy")
    ax1.legend(); ax1.grid(alpha=0.3)

    ax2.plot(epochs, loss, "o-", label="Train")
    ax2.plot(epochs, val_loss, "s-", label="Validation")
    ax2.axvline(config.HEAD_EPOCHS + 0.5, ls="--", c="grey", alpha=0.7,
                label="Fine-tune start")
    ax2.set_title("Loss"); ax2.set_xlabel("Epoch"); ax2.set_ylabel("Loss")
    ax2.legend(); ax2.grid(alpha=0.3)

    fig.suptitle("Training history (DenseNet121 transfer learning)")
    fig.tight_layout()
    fig.savefig(path, dpi=120, bbox_inches="tight")
    plt.close(fig)
    print("Saved training-history figure ->", path)


def main() -> None:
    config.ensure_dirs()
    tf.random.set_seed(config.SEED)

    print("Building datasets ...")
    train_ds, val_ds, test_ds = data_loader.get_datasets()
    class_weights = data_loader.compute_class_weights()
    print("Class weights:", class_weights)

    print("Building model ...")
    net = model_lib.build_model()

    callbacks = [
        tf.keras.callbacks.EarlyStopping(
            monitor="val_auc", mode="max", patience=4, restore_best_weights=True
        ),
        tf.keras.callbacks.ReduceLROnPlateau(
            monitor="val_loss", factor=0.3, patience=2, min_lr=1e-7
        ),
    ]

    # ----- Phase 1: train the head -----
    print("\n=== Phase 1: training classification head (base frozen) ===")
    model_lib.compile_model(net, learning_rate=config.HEAD_LR)
    h1 = net.fit(
        train_ds,
        validation_data=val_ds,
        epochs=config.HEAD_EPOCHS,
        class_weight=class_weights,
        callbacks=callbacks,
        verbose=2,
    )

    # ----- Phase 2: fine-tune the top of the backbone -----
    print("\n=== Phase 2: fine-tuning top layers of DenseNet121 ===")
    model_lib.unfreeze_top(net)
    model_lib.compile_model(net, learning_rate=config.FINETUNE_LR)
    h2 = net.fit(
        train_ds,
        validation_data=val_ds,
        epochs=config.FINETUNE_EPOCHS,
        class_weight=class_weights,
        callbacks=callbacks,
        verbose=2,
    )

    # ----- Save -----
    net.save(config.MODEL_PATH)
    print("\nSaved model ->", config.MODEL_PATH)
    _plot_history([h1, h2], config.FIGURES_DIR / "training_history.png")

    # ----- Evaluate & generate all report figures -----
    print("\n=== Evaluating on the held-out test set ===")
    metrics = evaluate.evaluate_model(net, test_ds)
    with open(config.METRICS_PATH, "w") as f:
        json.dump(metrics, f, indent=2)
    print("Saved metrics ->", config.METRICS_PATH)
    print(json.dumps(metrics, indent=2))


if __name__ == "__main__":
    main()
